name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.x'

      - name: Generate snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: AkshayMoolya
          svg_out_path: dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
